version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27071:27071"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
